#!/bin/bash

go install ./runner
go install ./run-preparer

result_writer() {
  [[ -t 0 ]] ||
    input=$(cat)

  if [[ -z $input ]]
  then
    echo no input received >&2
    return 1
  fi

  if [[ -z $1 ]]; then echo USAGE: result_writer treeish_id && return 1; fi
  treeish=$1

  echo appending note to $treeish >&2
  git notes --ref=tbd append -m"$input" $treeish
}

tree=HEAD^{tree}

run-preparer --treeish $tree | runner | result_writer $tree
