#!/bin/bash

runner() {
  [[ $# -ne 2 ]] && echo 'USAGE: runner script treeish_id' && return 1

  temp_dir=$(mktemp -d)

  git --work-tree $temp_dir checkout $2 -- .

  echo Running $1 in $temp_dir >&2
  (cd $temp_dir && $1)

}

result_writer() {
  [[ -t 0 ]] ||
    input=$(cat)

  if [[ -z $input ]]
  then
    echo no input received >&2
    return 1
  fi

  if [[ -z $1 ]]; then echo USAGE: result_writer treeish_id && return 1; fi
  treeish=$1

  echo appending note to $treeish >&2
  git notes --ref=tbd append -m"$input" $treeish
}

config_parser() {
  for dir in $(ls ci)
  do
    echo ci/${dir}/run
  done
}

tree=HEAD^{tree}

for script in $(config_parser)
do
  runner $script $tree | result_writer $tree
done
